// <auto-generated />
using System;
using Family_Feud.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Family_Feud.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130125339_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Family_Feud.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnswerTextEN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerTextPL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerTextEN = "Towel",
                            AnswerTextPL = "Ręcznik",
                            Points = 45,
                            QuestionId = 1,
                            Rank = 1
                        },
                        new
                        {
                            Id = 2,
                            AnswerTextEN = "Sunscreen",
                            AnswerTextPL = "Krem z filtrem",
                            Points = 25,
                            QuestionId = 1,
                            Rank = 2
                        },
                        new
                        {
                            Id = 3,
                            AnswerTextEN = "Umbrella",
                            AnswerTextPL = "Parasol",
                            Points = 15,
                            QuestionId = 1,
                            Rank = 3
                        },
                        new
                        {
                            Id = 4,
                            AnswerTextEN = "Water",
                            AnswerTextPL = "Woda",
                            Points = 10,
                            QuestionId = 1,
                            Rank = 4
                        },
                        new
                        {
                            Id = 5,
                            AnswerTextEN = "Snacks",
                            AnswerTextPL = "Przekąski",
                            Points = 5,
                            QuestionId = 1,
                            Rank = 5
                        },
                        new
                        {
                            Id = 6,
                            AnswerTextEN = "Dog",
                            AnswerTextPL = "Pies",
                            Points = 50,
                            QuestionId = 2,
                            Rank = 1
                        },
                        new
                        {
                            Id = 7,
                            AnswerTextEN = "Cat",
                            AnswerTextPL = "Kot",
                            Points = 35,
                            QuestionId = 2,
                            Rank = 2
                        },
                        new
                        {
                            Id = 8,
                            AnswerTextEN = "Fish",
                            AnswerTextPL = "Ryba",
                            Points = 10,
                            QuestionId = 2,
                            Rank = 3
                        },
                        new
                        {
                            Id = 9,
                            AnswerTextEN = "Bird",
                            AnswerTextPL = "Ptak",
                            Points = 5,
                            QuestionId = 2,
                            Rank = 4
                        });
                });

            modelBuilder.Entity("Family_Feud.Models.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeveloperEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeveloperName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RateLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Family_Feud.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HostUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Team1Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team2Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentQuestionId");

                    b.HasIndex("HostId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Family_Feud.Models.GameParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("GameParticipants");
                });

            modelBuilder.Entity("Family_Feud.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionTextEN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionTextPL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            CreatedByUserId = 1,
                            Difficulty = 1,
                            IsActive = true,
                            QuestionTextEN = "Name something people bring to the beach",
                            QuestionTextPL = "Wymień coś, co ludzie zabierają na plażę"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Animals",
                            CreatedByUserId = 1,
                            Difficulty = 1,
                            IsActive = true,
                            QuestionTextEN = "Name a popular pet",
                            QuestionTextPL = "Wymień popularne zwierzę domowe"
                        });
                });

            modelBuilder.Entity("Family_Feud.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 30, 12, 53, 39, 653, DateTimeKind.Utc).AddTicks(7590),
                            Email = "admin@familyfeud.com",
                            PasswordHash = "$2a$11$ZUAT4VZFGRShjI.GPv/4/OMOBp2qpCJPqy0cQmlin6dZ9/FbFtZ/.",
                            PreferredLanguage = "en",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Family_Feud.Models.Answer", b =>
                {
                    b.HasOne("Family_Feud.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Family_Feud.Models.Game", b =>
                {
                    b.HasOne("Family_Feud.Models.Question", "CurrentQuestion")
                        .WithMany()
                        .HasForeignKey("CurrentQuestionId");

                    b.HasOne("Family_Feud.Models.User", "Host")
                        .WithMany()
                        .HasForeignKey("HostId");

                    b.Navigation("CurrentQuestion");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Family_Feud.Models.GameParticipant", b =>
                {
                    b.HasOne("Family_Feud.Models.Game", "Game")
                        .WithMany("Participants")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Family_Feud.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Family_Feud.Models.Question", b =>
                {
                    b.HasOne("Family_Feud.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Family_Feud.Models.Game", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Family_Feud.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
